### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by RyanSquared** [ChickenNuggers/Astronomy#3]
- [x] Make Travis CI work with MoonScript
- [x] Fix tests
- [ ] Rewrite tests in busted/luacheck
  - [ ] Add `busted` as a dependency
  - [ ] Add `luacheck` as a dependency
